### ISSUE TITLE
Does Not Work on Temasek's CyanogenMod 13

### ISSUE THREAD

**Issue by VincentJoshuaET** [Reverp/Xposed-NougatNavigationBar#1]
I'm running an unofficial build of Temasek's CM13 with the April 2, 2016 Android security patch level.
[xposed_error_20160707_081331.txt](https://github.com/Reverp/Xposed-NougatNavigationBar/files/351145/xposed_error_20160707_081331.txt)

**Comment by michaelschattgen** [comment]
Thanks for the feedback. Will implement this tomorrow.

**Comment by Cloak253** [comment]
Small bug where the back and recent keys revert back. 



[xposed_error_20160706_204823.txt](https://github.com/Reverp/Xposed-NougatNavigationBar/files/351174/xposed_error_20160706_204823.txt)

**Comment by MSchattgen** [comment]
Just pushed a new version to Xposed, could you try for me please?

**Comment by michaelschattgen** [comment]
Just pushed a new version to Xposed, could you try for me please?
