### ISSUE TITLE
Icons are not of the same size

### ISSUE THREAD

**Issue by evyd13** [Reverp/Xposed-NougatNavigationBar#4]
You can see that clearly when drawing a line in an image editing program. Being the autist I am, I can see it with the naked eye.

**Comment by armaninyow** [comment]
I noticed the triangle looks smaller. I also compared this buttons to the Marshmallow buttons.

**Comment by VincentJoshuaET** [comment]
http://imgur.com/a/WPI1G

On my 240dpi phone, it is the same size. But on my 160dpi tablet, it isn't.

**Comment by decoy-octopus** [comment]
Also, the circle button needs to move a little to the right. And when I'm sizing down the statusbar with GravityBox the icons become waaay too small.

**Comment by MSchattgen** [comment]
Just pushed a new version to Xposed, could you try for me please?

**Comment by michaelschattgen** [comment]
Just pushed a new version to Xposed, could you try for me please?

**Comment by theoqrz** [comment]
I still think the squared button could be smaller

**Comment by timea-techgirl** [comment]
The square button is still bigger.
